#create brands
makes = [{:name => "Alfa Romeo"}, {:name => "Asia Motors"}, {:name => "Aston Martin"}, {:name => "Audi"}, {:name => "Bentley"}, {:name => "BMW"}, {:name => "Cadillac"}, {:name => "Chevrolet"}, {:name => "Chrysler"}, {:name => "Citroen"}, {:name => "Daewoo"}, {:name => "Daihatsu"}, {:name => "Dodge"}, {:name => "Fiat"}, {:name => "Ford"}, {:name => "Honda"}, {:name => "Hummer"}, {:name => "Hyundai"}, {:name => "Jaguar"}, {:name => "Jeep"}, {:name => "Kia"}, {:name => "Mazda"}, {:name => "Mercedes"}, {:name => "Mini"}, {:name => "Mitsubishi"}, {:name => "Nissan"}, {:name => "Opel"}, {:name => "Peugeot"}, {:name => "Renault"}, {:name => "Seat"}, {:name => "Skoda"}, {:name => "Subaru"}, {:name => "Suzuki"}, {:name => "Toyota"}, {:name => "VolkesWagen"}, {:name => "Volvo"}]
makes.each do |make|
  Make.create! make
end

#create models
models = [{:name => "Giulietta3", :make_id => 1}, {:name => "8C Competizione", :make_id => 1}, {:name => "Brera", :make_id => 1}, {:name => "MiTo", :make_id => 1}, {:name => "Spider", :make_id => 1}, {:name => "159", :make_id => 1}, {:name => "GT", :make_id => 1}, {:name => "147", :make_id => 1}, {:name => "GTV", :make_id => 1}, {:name => "156", :make_id => 1}, {:name => "166", :make_id => 1}, {:name => "145", :make_id => 1}, {:name => "146", :make_id => 1}, {:name => "Rocsta", :make_id => 2}, {:name => "Cygnet", :make_id => 3}, {:name => "DBS", :make_id => 3}, {:name => "Rapide", :make_id => 3}, {:name => "V12", :make_id => 3}, {:name => "V8", :make_id => 3}, {:name => "DB9", :make_id => 3}, {:name => "DB7", :make_id => 3}, {:name => "Volante", :make_id => 3}, {:name => "Virage", :make_id => 3}, {:name => "Yares", :make_id => 3}, {:name => "A1", :make_id => 4}, {:name => "A2", :make_id => 4}, {:name => "A3", :make_id => 4}, {:name => "A4", :make_id => 4}, {:name => "A5", :make_id => 4}, {:name => "A6", :make_id => 4}, {:name => "A7", :make_id => 4}, {:name => "A8", :make_id => 4}, {:name => "S3", :make_id => 4}, {:name => "S4", :make_id => 4}, {:name => "S5", :make_id => 4}, {:name => "S6", :make_id => 4}, {:name => "S7", :make_id => 4}, {:name => "S8", :make_id => 4}, {:name => "RS3", :make_id => 4}, {:name => "RS4", :make_id => 4}, {:name => "RS5", :make_id => 4}, {:name => "RS6", :make_id => 4}, {:name => "Q3", :make_id => 4}, {:name => "Q5", :make_id => 4}, {:name => "Q7", :make_id => 4}, {:name => "Continental", :make_id => 5}, {:name => "Mulsanne", :make_id => 5}, {:name => "Brooklands", :make_id => 5}, {:name => "Azure", :make_id => 5}, {:name => "Arnage", :make_id => 5}, {:name => "8-series", :make_id => 6}, {:name => "7-series", :make_id => 6}, {:name => "6-series", :make_id => 6}, {:name => "5-series", :make_id => 6}, {:name => "3-series", :make_id => 6}, {:name => "1-series", :make_id => 6}, {:name => "Z1", :make_id => 6}, {:name => "Z3", :make_id => 6}, {:name => "Z4", :make_id => 6}, {:name => "Z8", :make_id => 6}, {:name => "X1", :make_id => 6}, {:name => "X3", :make_id => 6}, {:name => "X5", :make_id => 6}, {:name => "X6", :make_id => 6}, {:name => "i320", :make_id => 6}, {:name => "BLS", :make_id => 7}, {:name => "STS", :make_id => 7}, {:name => "Escalade", :make_id => 7}, {:name => "SRX", :make_id => 7},
          {:name => "XLR", :make_id => 7},
          {:name => "CTS", :make_id => 7},
          {:name => "Seville", :make_id => 7},
          {:name => "Eldorado", :make_id => 7},
          {:name => "Orlando", :make_id => 8},
          {:name => "Volt", :make_id => 8},
          {:name => "Spark", :make_id => 8},
          {:name => "Cruze", :make_id => 8},
          {:name => "HHR", :make_id => 8},
          {:name => "Captiva", :make_id => 8},
          {:name => "Epica", :make_id => 8},
          {:name => "Aveo", :make_id => 8},
          {:name => "Evanda", :make_id => 8},
          {:name => "Kalos", :make_id => 8},
          {:name => "Matiz", :make_id => 8},
          {:name => "Nubira", :make_id => 8},
          {:name => "Tacuma", :make_id => 8},
          {:name => "TrailBlazer", :make_id => 8},
          {:name => "Tahoe", :make_id => 8},
          {:name => "Camaro", :make_id => 8},
          {:name => "Blazer", :make_id => 8},
          {:name => "Trans Sport", :make_id => 8},
          {:name => "Corvette", :make_id => 8},
          {:name => "Caprice", :make_id => 8},
          {:name => "Lumina", :make_id => 8},
          {:name => "Corsica", :make_id => 8},
          {:name => "Beretta", :make_id => 8},
          {:name => "PT Cruiser", :make_id => 9},
          {:name => "300C", :make_id => 9},
          {:name => "Crossfire", :make_id => 9},
          {:name => "Sebring", :make_id => 9},
          {:name => "300M", :make_id => 9},
          {:name => "Stratus", :make_id => 9},
          {:name => "New Yorker", :make_id => 9},
          {:name => "Neon", :make_id => 9},
          {:name => "Viper", :make_id => 9},
          {:name => "Vision", :make_id => 9},
          {:name => "Daytona", :make_id => 9},
          {:name => "Grand Voyager", :make_id => 9},
          {:name => "Voyager", :make_id => 9},
          {:name => "Saratoga", :make_id => 9},
          {:name => "Jumper", :make_id => 10},
          {:name => "Jumpy", :make_id => 10},
          {:name => "DS5", :make_id => 10},
          {:name => "DS3", :make_id => 10},
          {:name => "Nemo", :make_id => 10},
          {:name => "C-Crosser", :make_id => 10},
          {:name => "C-Zero", :make_id => 10},
          {:name => "C1", :make_id => 10},
          {:name => "C2", :make_id => 10},
          {:name => "C3", :make_id => 10},
          {:name => "C4", :make_id => 10},
          {:name => "C5", :make_id => 10},
          {:name => "C6", :make_id => 10},
          {:name => "C8", :make_id => 10},
          {:name => "Xsara", :make_id => 10},
          {:name => "Berlingo", :make_id => 10},
          {:name => "Saxo", :make_id => 10},
          {:name => "Evasion", :make_id => 10},
          {:name => "Xantia", :make_id => 10},
          {:name => "ZX", :make_id => 10},
          {:name => "AX", :make_id => 10},
          {:name => "XM", :make_id => 10},
          {:name => "BX", :make_id => 10},
          {:name => "Nubira", :make_id => 11},
          {:name => "Lanus", :make_id => 11},
          {:name => "Juliette", :make_id => 11},
          {:name => "Siriron", :make_id => 12},
          {:name => "Terious", :make_id => 12},
          {:name => "Charger", :make_id => 13},
          {:name => "Dorango", :make_id => 13},
          {:name => "Ram", :make_id => 13},
          {:name => "Punto", :make_id => 14},
          {:name => "Bravo", :make_id => 14},
          {:name => "Panda", :make_id => 14},
          {:name => "Focus", :make_id => 15},
          {:name => "Mustang", :make_id => 15},
          {:name => "Mondea", :make_id => 15},
          {:name => "City", :make_id => 16},
          {:name => "Civic", :make_id => 16},
          {:name => "Accord", :make_id => 16},
          {:name => "HRV", :make_id => 16},
          {:name => "H2", :make_id => 17},
          {:name => "H3", :make_id => 17},
          {:name => "Elantra", :make_id => 18},
          {:name => "i10", :make_id => 18},
          {:name => "i20", :make_id => 18},
          {:name => "i30", :make_id => 18},
          {:name => "i40", :make_id => 18},
          {:name => "Matrix", :make_id => 18},
          {:name => "Sonnata", :make_id => 18},
          {:name => "XK", :make_id => 19},
          {:name => "X-Type", :make_id => 19},
          {:name => "S-Type", :make_id => 19},
          {:name => "Wrangler", :make_id => 20},
          {:name => "Cherokee", :make_id => 20},
          {:name => "Commander", :make_id => 20},
          {:name => "Pride", :make_id => 21},
          {:name => "Cerato", :make_id => 21},
          {:name => "Carens", :make_id => 21},
          {:name => "Picanot", :make_id => 21},
          {:name => "Rio", :make_id => 21},
          {:name => "3", :make_id => 22},
          {:name => "2", :make_id => 22},
          {:name => "5", :make_id => 22},
          {:name => "A-Class", :make_id => 23},
          {:name => "B-Class", :make_id => 23},
          {:name => "C-Class", :make_id => 23},
          {:name => "E-Class", :make_id => 23},
          {:name => "GLK", :make_id => 23},
          {:name => "CLS", :make_id => 23},
          {:name => "SLK", :make_id => 23},
          {:name => "Cooper", :make_id => 24},
          {:name => "Cooper S", :make_id => 24},
          {:name => "Countryman", :make_id => 24},
          {:name => "Clubman", :make_id => 24},
          {:name => "Lancer", :make_id => 25},
          {:name => "Colt", :make_id => 25},
          {:name => "Pajero", :make_id => 25},
          {:name => "Sunny", :make_id => 26},
          {:name => "Tiida", :make_id => 26},
          {:name => "370Z", :make_id => 26},
          {:name => "Astra", :make_id => 27},
          {:name => "Vectra", :make_id => 27},
          {:name => "Corsa", :make_id => 27},
          {:name => "307", :make_id => 28},
          {:name => "308", :make_id => 28},
          {:name => "206", :make_id => 28},
          {:name => "207", :make_id => 28},
          {:name => "406", :make_id => 28},
          {:name => "Cleo", :make_id => 29},
          {:name => "Sandero", :make_id => 29},
          {:name => "Fluence", :make_id => 29},
          {:name => "Logan", :make_id => 29},
          {:name => "Megan", :make_id => 29},
          {:name => "Ibiza", :make_id => 30},
          {:name => "Leon", :make_id => 30},
          {:name => "Cordoba", :make_id => 30},
          {:name => "Octavia", :make_id => 31},
          {:name => "Impreza", :make_id => 32},
          {:name => "Swift", :make_id => 33},
          {:name => "Alto", :make_id => 33},
          {:name => "Corolla", :make_id => 34},
          {:name => "Yaris", :make_id => 34},
          {:name => "Land Cruiser", :make_id => 34},
          {:name => "Jetta", :make_id => 35},
          {:name => "Passat", :make_id => 35},
          {:name => "EOS", :make_id => 35},
          {:name => "Golf", :make_id => 35},
          {:name => "CC", :make_id => 35},
          {:name => "Beetle", :make_id => 35},
          {:name => "S60", :make_id => 36},
          {:name => "S80", :make_id => 36},
          {:name => "V60", :make_id => 36}]
models.each do |car_model|
  CarModel.create! car_model
end

#create owners
owners = [{:name => "Adam Samir", :email => "asamir@hotmail.com", :phone => "22345455", :mobile => "01232453765"},
          {:name => "Mohamed Ali", :email => "moh_ali23@yahoo.com", :phone => "33483728", :mobile => "01028448430"},
          {:name => "Mahmoud Osama", :email => "mahmoud.osama@gmail.com", :phone => "29573758", :mobile => "01247386016"},
          {:name => "Alaa Maged", :email => "a.maged@live.com", :phone => "352618904", :mobile => "01134860173"}]
owners.each do |owner|
  Owner.create! owner
end

#create cars
cars = [{:description => "A/T fairly new", :price => 350000, :year => 2013, :seats => 4, :doors => 4, :car_model_id => 65, :owner_id => 1},
        {:description => "M/T good shape", :price => 350000, :year => 2012, :seats => 4, :car_model_id => 80, :owner_id => 2},
        {:description => "Good shape, barely used", :price => 350000, :year => 2008, :car_model_id => 6, :owner_id => 3},
        {:description => "please call for details", :price => 350000, :year => 2012, :seats => 4, :doors => 4, :car_model_id => 40, :owner_id => 4}]
cars.each do |car|
  Car.create! car
end

#create users
users = [{:owner_id => 1, :password => "12345", :password_confirmation => "12345"},
         {:owner_id => 2, :password => "12345", :password_confirmation => "12345"},
         {:owner_id => 3, :password => "12345", :password_confirmation => "12345"},
         {:owner_id => 4, :password => "12345", :password_confirmation => "12345"}]
users.each do |usr|
  User.create! usr
end
